import React, { useEffect } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script';

function createMarkup(content) {
    return { __html: content };
}

function Blogpost({ blog }) {
    useEffect(() => {
        let fbCommentsElem = document.getElementById("fb-comments");
        fbCommentsElem.innerHTML = `
            <div id="fb-root"></div>
            <div class="fb-comments" data-href="http://127.0.0.1:3000${window.location.pathname}" data-width="100%" data-numposts="5"></div>
        `;
    })
    return (
        <>
            <Head>
                <title>{blog && blog.title} - Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h1><Link href={"/blogpost/" + blog && blog.slug}><a className="text-dark">{blog && blog.title }</a></Link></h1>
                <p className="text-muted mb-1">Published by {blog && blog.author}</p>
                <hr />
                <div dangerouslySetInnerHTML={createMarkup(blog && blog.content)}></div>
                <hr />
                <div id="fb-comments"></div>
            </div>
            <Script src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v15.0" async defer crossOrigin="anonymous"></Script>
        </>
    )
}

export async function getServerSideProps(context) {
    const { slug } = context.query;
    let data = await fetch('http://localhost:3000/api/getblog?slug=' + slug);
    let blog = await data.json();
    return {
        props: {
            blog
        }
    }
}

export default Blogpost;
