import React from 'react'
import Head from 'next/head'

function About() {
    return (
        <>
            <Head>
                <title>About - Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h1>About Blog</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste ipsum quo debitis at libero assumenda. Quidem rem tenetur aperiam corrupti dolores commodi rerum neque quia iusto tempora distinctio delectus molestiae voluptatibus ipsum ipsam totam enim in, deleniti facere suscipit accusantium quisquam at provident quaerat. Molestias eius repellat cum delectus consequuntur, soluta fuga libero hic itaque. In veritatis magni suscipit esse temporibus assumenda quod. Architecto repellendus voluptatem nobis blanditiis hic? Sapiente nobis maxime modi repellendus distinctio aut laboriosam ad natus sit. Ut ipsa quaerat voluptatibus ab fuga minus. Placeat quisquam nesciunt ratione maxime porro eaque laboriosam qui dolores doloribus perferendis, saepe, delectus ullam reiciendis. Natus incidunt quia veniam perspiciatis vero pariatur accusamus neque! Aspernatur magnam nesciunt exercitationem accusantium esse vitae!</p>
            </div>
        </>
    )
}

export default About