import Head from 'next/head'
import Link from 'next/link'

function Blog({ blogs }) {
    return (
        <>
            <Head>
                <title>Blog - Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h1>Browse coding articles</h1>
                <hr />
                {blogs.map((blog) => {
                    return <div key={blog.slug} className="border shadow-sm p-3 rounded my-3">
                        <h3><a className="text-dark" href={"/blogpost/" + blog.slug}>{blog.title}</a></h3>
                        <p className="text-muted mb-1">Published by {blog.author}</p>
                        <p className="mb-2">{blog.tagline}</p>
                        <Link href={"/blogpost/" + blog.slug}><a className="btn btn-sm btn-outline-danger">Read More &raquo;</a></Link>
                    </div>
                })}
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    let data = await fetch('http://localhost:3000/api/getblogs');
    let blogs = await data.json();
    return {
        props: {
            blogs
        }
    }
}

export default Blog;
