import React from 'react'
import Head from 'next/head'

function Contact() {
    return (
        <>
            <Head>
                <title>Contact - Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h1>Contact Me</h1>
                <form action="/api/contact" method="post">
                    <div className="form-group">
                        <label htmlFor="name">Name</label>
                        <input type="text" className="form-control" id="name" name="name" placeholder="Enter your full name" />
                    </div>
                    <div className="form-group">
                        <label htmlFor="email">Email</label>
                        <input type="email" className="form-control" id="email" name="email" placeholder="Enter your email address" />
                    </div>
                    <div className="form-group">
                        <label htmlFor="phone">Phone number (with country code)</label>
                        <input type="text" className="form-control" id="phone" name="phone" placeholder="Enter your phone number" />
                    </div>
                    <div className="form-group">
                        <label htmlFor="message">Message</label>
                        <textarea className="form-control" id="message" name="message" rows={4} placeholder="Describe your concern here" />
                    </div>
                    <button type="submit" className="btn btn-danger">Submit</button>
                </form>
            </div>
        </>
    )
}

export default Contact