import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="jumbotron text-center">
        <div className="container">
          <h1 className="font-weight-bold">Welcome to HuntingCoder!</h1>
          <p className="lead text-muted">
            This is a new blog created using nextjs and bootstrap. Browse all the coding blogs for free. Contact me for any kind of queries.
          </p>
          <p>
            <Link href="/blog"><a className="btn btn-danger my-2">Browse Coding Articles &raquo;</a></Link>
            <Link href="/contact"><a className="btn btn-primary mx-2 my-2">Contact Me &raquo;</a></Link>
          </p>
        </div>
      </div>
    </>
  )
}
