import React from 'react'
import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router'

function Search({ blogs }) {
    const router = useRouter();
    const { query } = router.query;
    return (
        <>
            <Head>
                <title>Search results for &quot;{query}&quot; - Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h1>Search results for &quot;{query}&quot;</h1>
                <hr />
                {blogs.length === 0 ? <div>
                    <h4>No search results are available for &quot;{query}&quot;</h4>
                    <p>Suggestions:</p>

                    <ul>
                        <li>Make sure that all words are spelled correctly.</li>
                        <li>Try different keywords.</li>
                        <li>Try more general keywords.</li>
                    </ul>
                </div> : blogs.map((blog) => {
                    return <div key={blog.slug} className="border shadow-sm p-3 rounded my-3">
                        <h3><a className="text-dark" href={"/blogpost/" + blog.slug}>{blog.title}</a></h3>
                        <p className="text-muted mb-1">Published by {blog.author}</p>
                        <p className="mb-2">{blog.tagline}</p>
                        <Link href={"/blogpost/" + blog.slug}><a className="btn btn-sm btn-outline-danger">Read More &raquo;</a></Link>
                    </div>
                })}
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    let { query } = context.query;
    let data = await fetch('http://localhost:3000/api/search?query=' + query);
    let blogs = await data.json();
    return {
        props: {
            blogs
        }
    }
}

export default Search